### ISSUE TITLE
AFKParticleの実装

### ISSUE THREAD

**Issue by book000** [jaoafa/AwayFromKeyboard#1]
以下の項目のパーティクルのパラメーターが決まっておらず、未実装。また1.16.5でさらに追加される予定あり

- [x] `EXPLOSION_LARGE`
- [x] `SMOKE_NORMAL`
- [x] `SMOKE_LARGE`
- [x] `SPELL`
- [x] `SPELL_INSTANT`
- [x] `SPELL_MOB`
- [x] `SPELL_MOB_AMBIENT`
- [x] `SPELL_WITCH`
- [x] `PORTAL`
- [x] `FLAME`
- [x] `LAVA`
- [x] `SLIME`
- [x] `HEART`
- [x] `BARRIER`
- [x] `ITEM_CRACK`
- [x] `BLOCK_CRACK`
- ~~`BLOCK_DUST`~~
- ~~`ITEM_TAKE`~~

とりあえずパラメーターが決まったらGoogleドキュメントとできればここに書いてください。アサインされているメンバー以外でも可

**Comment by yuuahp** [comment]
✅EXPLOSION_LARGE

**Comment by yuuahp** [comment]
✅SMOKE_NORMAL

**Comment by yuuahp** [comment]
✅SMOKE_LARGE

**Comment by yuuahp** [comment]
✅SPELL

**Comment by yuuahp** [comment]
✅SPELL INSTANT

**Comment by yuuahp** [comment]
✅SPELL MOB

**Comment by yuuahp** [comment]
✅SPELL MOB AMBIENT

**Comment by yuuahp** [comment]
✅PORTAL

**Comment by yuuahp** [comment]
✅FLAME

**Comment by yuuahp** [comment]
✅LAVA

**Comment by yuuahp** [comment]
✅SLIME
✅HEART
✅BARRIER

**Comment by yuuahp** [comment]
✅ITEM_CRACK
 ✅BLOCK_CRACK
 💥BLOCK_DUST (なんもでてきません)
 💥ITEM_TAKE (なんもでてきません)

**Comment by yuuahp** [comment]
２つを除きすべて完了しました
