### ISSUE TITLE
AFKParticleの実装 (1.16.5版)

### ISSUE THREAD

**Issue by book000** [jaoafa/AwayFromKeyboard#3]
以下の項目のパーティクルのパラメーターが決まっておらず、未実装。1.14から1.16で実装されたパーティクル

- [x] `SQUID_INK`
- [x] `BUBBLE_POP`
- [x] `CURRENT_DOWN`
- [x] `BUBBLE_COLUMN_UP`
- [x] `NAUTILUS`
- [x] `DOLPHIN`
- [x] `SNEEZE`
- [x] `CAMPFIRE_COSY_SMOKE`
- [x] `CAMPFIRE_SIGNAL_SMOKE`
- [x] `COMPOSTER`
- [x] `FLASH`
- [x] `FALLING_LAVA`
- [x] `LANDING_LAVA`
- [x] `FALLING_WATER`
- [x] `DRIPPING_HONEY`
- [x] `FALLING_HONEY`
- [x] `LANDING_HONEY`
- [x] `FALLING_NECTAR`
- [x] `SOUL_FIRE_FLAME`
- [x] `ASH`
- [x] `CRIMSON_SPORE`
- [x] `WARPED_SPORE`
- [x] `SOUL`
- [x] `DRIPPING_OBSIDIAN_TEAR`
- [x] `FALLING_OBSIDIAN_TEAR`
- [x] `LANDING_OBSIDIAN_TEAR`
- [x] `REVERSE_PORTAL`
- [x] `WHITE_ASH`

とりあえずパラメーターが決まったらGoogleドキュメントとできればここに書いてください。アサインされているメンバー以外でも可

**Comment by yuuahp** [comment]
✅SNEESEまで

**Comment by yuuahp** [comment]
✅COMPOSTERまで
⚠FLASH (直視できない、ちかちかする、目が死ぬ)

**Comment by yuuahp** [comment]
✅LANDING_HONEYまで

**Comment by book000** [comment]
FLASH無し。

**Comment by yuuahp** [comment]
✅全て完了しました

**Comment by yuuahp** [comment]
写真、正方形になってないやつ全部撮り直していいですか

**Comment by book000** [comment]
iiyo

**Comment by book000** [comment]
解放順どうしよ

**Comment by yuuahp** [comment]
全部取り直しました（欠落していたところも撮りました）
